# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 17:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('tid', models.IntegerField(primary_key=True, serialize=False)),
                ('tweet', models.CharField(max_length=140)),
                ('ts', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserLoginCredentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pwd', models.CharField(max_length=255)),
                ('ts', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('uid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=42)),
                ('handle', models.CharField(max_length=42, unique=True)),
                ('email_id', models.EmailField(max_length=255, unique=True)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('img', models.ImageField(upload_to='/profile_pic/')),
                ('joined_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='userlogincredentials',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tweeter.UserProfile'),
        ),
        migrations.AddField(
            model_name='tweet',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tweeter.UserProfile'),
        ),
        migrations.AddField(
            model_name='follow',
            name='followed_uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed', to='tweeter.UserProfile'),
        ),
        migrations.AddField(
            model_name='follow',
            name='follower_uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='tweeter.UserProfile'),
        ),
    ]
