# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 18:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tweeter', '0002_auto_20161113_2247'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=42)),
                ('handle', models.CharField(max_length=42, unique=True)),
                ('email_id', models.EmailField(max_length=255, unique=True)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('img', models.ImageField(upload_to='/profile_pic/')),
                ('joined_on', models.DateTimeField(auto_now_add=True)),
                ('following', models.ManyToManyField(to='tweeter.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='follow',
            name='followed_uid',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='follower_uid',
        ),
        migrations.AlterField(
            model_name='tweet',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tweeter.User'),
        ),
        migrations.AlterField(
            model_name='userlogincredentials',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tweeter.User'),
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
